neo.Plugin={id:"Plugin",name:"PluginPlugin",cssClass:"plugin-plugin",moduleClass:"PluginModule",angularBootstrap:function($el,plugin){if(!$el.hasClass("neo-asset")){return;
}try{var $injector=$el.injector();
if(!angular.isDefined($injector)){angular.bootstrap(angular.element("#canvas"),["webcomApp"]);
$injector=$el.injector();
}else{$injector.invoke(function($compile){var scope=$el.scope();
$compile($el)(scope);
});
}webcomApp.controller(plugin.id+"PluginController",plugin.ngPluginController);
$el.attr("data-ng-controller",plugin.id+"PluginController");
}catch(e){console.error("Could not bootstrap",$el);
}},bootstrap:function($el){if(!$el.hasClass("neo-asset")){return;
}var moduleClassString=$el.attr("data-module-class");
var moduleClass=null;
try{if(moduleClassString){moduleClass=eval(moduleClassString);
}}catch(e){}if(moduleClass&&typeof(moduleClass)=="object"){neo.PropertiesNgModule.clickCloak.addClickCloak($el);
if(moduleClass&&typeof(moduleClass.pluginInit)=="function"){moduleClass.pluginInit($el);
}$el.click(function(event){if(!neo.PropertiesPanelModule.isAssetSaving()){neo.Plugin.lastEvent=event;
moduleClass.select($el);
}});
$el.dblclick(function(){if(!neo.PropertiesPanelModule.isAssetSaving()){var $ppScope=$("#properties-module-shell").scope();
$ppScope.onSwapPropertyPanel();
}});
}},enableElement:function($el){$el.attr({"data-module-class":this.moduleClass});
if(typeof(this.construct)=="function"){this.construct($el);
}neo.Plugin.bootstrap($el);
},enableAllElements:function(){var t=this;
$("."+this.cssClass).each(function(){t.enableElement($(this));
});
},extend:function(childClass){var plugin=$.extend({},this,childClass);
if(!childClass.cssClass&&childClass.id){plugin.cssClass=childClass.id.toLowerCase()+"-plugin";
}if(!childClass.moduleClass&&childClass.id){plugin.moduleClass="neo."+childClass.id+"Module";
}if(!childClass.name&&childClass.id){plugin.name=childClass.id+"Plugin";
}webcomApp.registerPlugin(plugin);
if(typeof(plugin.init)=="function"){plugin.init();
}return plugin;
},};
neo.SiteSearchPlugin=neo.Plugin.extend({id:"SiteSearch",name:"SiteSearchPlugin",template:$(".sitesearch-plugin-inner").html(),cssClass:"sitesearch-plugin",setScrollBar:function(){$("#neo-sitesearch-result-modal .modal-bottom").mCustomScrollbar({advanced:{updateOnContentResize:true,autoScrollOnFocus:true}});
},enableElement:function($el,useTemplate){if(useTemplate&&$el.find(".ss-container").size()==0){$el.find(".neo-asset-inner").html(neo.SiteSearchPlugin.template);
}$el.attr({"data-ng-controller":this.name+"Controller","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit()","data-module-class":this.moduleClass,"data-ng-submit":"triggerSearch();"});
if(typeof(neo.SiteSearchModule)!="undefined"){neo.PropertiesNgModule.clickCloak.addClickCloak($el);
}neo.Plugin.angularBootstrap($el,this);
},ngPluginController:function($scope,$rootScope,$element){$scope.select=function(){if(typeof(neo.SiteSearchModule)=="object"){if(typeof console!="undefined"){console.log("SiteSearch Clicked, do MODULE stuff");
}neo.SiteSearchModule.select($element);
}else{if(typeof console!="undefined"){console.log("SiteSearch Clicked, do plugin stuff");
}}};
$scope.selectAndEdit=function(){if(typeof(neo.SiteSearchModule)=="object"){var $ppScope=$("#properties-module-shell").scope();
if(!$("#properties-module-shell").hasClass("active")){neo.SiteSearchModule.select($element);
}$ppScope.onSwapPropertyPanel();
}};
$scope.triggerSearch=function(){var searchTerm=$element.find(".ss-text").val();
if(searchTerm.length>0){$element.find(".ss-loading").css("display","block");
var domain=builderSettings.siteDomain;
var urlSearch=builderSettings.sitesearchUrl;
$.ajax({url:urlSearch,type:"post",dataType:"jsonp",data:{searchTerm:searchTerm,domainUrl:domain},success:function(responseText){$element.find(".ss-loading").css("display","none");
$scope.buildSiteSearchResult(responseText);
},error:function(requestText,statusText){$element.find(".ss-loading").css("display","none");
if(typeof console!="undefined"){console.log(requestText);
console.log(statusText);
}}});
}};
$scope.buildSiteSearchResult=function(responseText){var searchResultList="";
for(var i=0;
i<responseText.documents.length;
i++){var o=responseText.documents[i];
searchResultList+='<div><h4><a href="'+o.url+'">'+(o.title||o.url)+"</a></h4>"+o.content+"</div>";
}if(searchResultList.trim().length==0){searchResultList="<div>No Results found.</div>";
}$("#neo-sitesearch-result-modal .modal-bottom").html(searchResultList);
$("#neo-sitesearch-result-modal").css("display","block");
$("#neo-sitesearch-result-modal").addClass("modal-show");
$("#neo-sitesearch-result-modal .modal-x").on("click",function(){$("#neo-sitesearch-result-modal").removeClass("modal-show");
$("#neo-sitesearch-result-modal").css("display","none");
});
neo.SiteSearchPlugin.setScrollBar();
$("#neo-sitesearch-result-modal .modal-bottom").mCustomScrollbar("update");
};
$scope.closeSearchResult=function(){$("#neo-sitesearch-result-modal").css("display","none");
};
},});
webcomApp.controller("SiteSearchPluginController",neo.SiteSearchPlugin.ngPluginController);
webcomApp.controller("neo.SiteSearchPlugin.ngPluginController",neo.SiteSearchPlugin.ngPluginController);
$("#neo-sitesearch-result-modal").appendTo("body");
$('<div class="ss-modal-overlay"></div>').appendTo("body");
var WebCom_Components_Form_Element_TYPE={TEXTBOX:"TextBox",TEXTAREA:"TextArea",DROPDOWN:"DropDown",MULTISELECT:"MultiSelect",RADIOBUTTON:"RadioButton",CHECKBOX:"Checkbox",EMAIL:"Email",PERSON_NAME:"PersonName",ADDRESS:"Address",PARAGRAPH:"Paragraph",SUBMIT:"Submit"};
var WebCom_Components_Form_Element_LAYOUT={ONE_COLUMN:"onecolumn",TWO_COLUMN:"twocolumns",THREE_COLUMN:"threecolumns"};
var WebCom_Components_Form_Element_LABEL_POSITION={TOP:"top",BOTTOM:"bottom",LEFT:"left",RIGHT:"right"};
var WebCom_Components_Form_Element_SCHEMA={US:"us",INTERNATIONAL:"international"};
var WebCom_Components_Form_Element_OPTION_TYPE={US:"usastates",US_ABBREV:"usastates_abbrev",COUNTRIES:"countries",CURRENCIES:"currencies",CREDITCARDS:"creditcards",HOURS:"hours"};
var WebCom_Components_Form_Element_OPTION_PREDEFINED={days:[{value:"Monday"},{value:"Tuesday"},{value:"Wednesday"},{value:"Thursday"},{value:"Friday"},{value:"Saturday"},{value:"Sunday"}],hours:[{value:"1:00 AM"},{value:"2:00 AM"},{value:"3:00 AM"},{value:"4:00 AM"},{value:"5:00 AM"},{value:"6:00 AM"},{value:"7:00 AM"},{value:"8:00 AM"},{value:"9:00 AM"},{value:"10:00 AM"},{value:"11:00 AM"},{value:"12:00 AM"},{value:"1:00 PM"},{value:"2:00 PM"},{value:"3:00 PM"},{value:"4:00 PM"},{value:"5:00 PM"},{value:"6:00 PM"},{value:"7:00 PM"},{value:"8:00 PM"},{value:"9:00 PM"},{value:"10:00 PM"},{value:"11:00 PM"},{value:"12:00 PM"}],usastates:[{value:"Alabama"},{value:"Alaska"},{value:"Arizona"},{value:"Arkansas"},{value:"California"},{value:"Colorado"},{value:"Connecticut"},{value:"Delaware"},{value:"District Of Columbia"},{value:"Florida"},{value:"Georgia"},{value:"Hawaii"},{value:"Idaho"},{value:"Illinois"},{value:"Indiana"},{value:"Iowa"},{value:"Kansas"},{value:"Kentucky"},{value:"Louisiana"},{value:"Maine"},{value:"Maryland"},{value:"Massachusetts"},{value:"Michigan"},{value:"Minnesota"},{value:"Mississippi"},{value:"Missouri"},{value:"Montana"},{value:"Nebraska"},{value:"Nevada"},{value:"New Hampshire"},{value:"New Jersey"},{value:"New Mexico"},{value:"New York"},{value:"North Carolina"},{value:"North Dakota"},{value:"Ohio"},{value:"Oklahoma"},{value:"Oregon"},{value:"Pennsylvania"},{value:"Rhode Island"},{value:"South Carolina"},{value:"South Dakota"},{value:"Tennessee"},{value:"Texas"},{value:"Utah"},{value:"Vermont"},{value:"Virginia"},{value:"Washington"},{value:"West Virginia"},{value:"Wisconsin"},{value:"Wyoming"}],usastates_abbrev:[{label:"Alabama",value:"AL"},{label:"Alaska",value:"AK"},{label:"Arizona",value:"AZ"},{label:"Arkansas",value:"AR"},{label:"California",value:"CA"},{label:"Colorado",value:"CO"},{label:"Connecticut",value:"CT"},{label:"Delaware",value:"DE"},{label:"District Of Columbia",value:"DC"},{label:"Florida",value:"FL"},{label:"Georgia",value:"GA"},{label:"Hawaii",value:"HI"},{label:"Idaho",value:"ID"},{label:"Iowa",value:"IA"},{label:"Illinois",value:"IL"},{label:"Indiana",value:"IN"},{label:"Kansas",value:"KS"},{label:"Kentucky",value:"KY"},{label:"Louisiana",value:"LA"},{label:"Maine",value:"ME"},{label:"Maryland",value:"MD"},{label:"Massachusetts",value:"MA"},{label:"Michigan",value:"MI"},{label:"Minnesota",value:"MN"},{label:"Mississippi",value:"MS"},{label:"Missouri",value:"MO"},{label:"Montana",value:"MT"},{label:"North Carolina",value:"NC"},{label:"North Dakota",value:"ND"},{label:"Nebraska",value:"NE"},{label:"New Hampshire",value:"NH"},{label:"New Jersey",value:"NJ"},{label:"New Mexico",value:"NM"},{label:"Nevada",value:"NV"},{label:"New York",value:"NY"},{label:"Ohio",value:"OH"},{label:"Oklahoma",value:"OK"},{label:"Oregon",value:"OR"},{label:"Pennsylvania",value:"PA"},{label:"Rhode Island",value:"RI"},{label:"South Carolina",value:"SC"},{label:"South Dakota",value:"SD"},{label:"Tennessee",value:"TN"},{label:"Texas",value:"TX"},{label:"Utah",value:"UT"},{label:"Vermont",value:"VT"},{label:"Virginia",value:"VA"},{label:"Washington",value:"WA"},{label:"West Virginia",value:"WV"},{label:"Wisconsin",value:"WI"},{label:"Wyoming",value:"WY"}],countries:[{value:"United States"},{value:"Afghanistan"},{value:"Albania"},{value:"Algeria"},{value:"American Samoa"},{value:"Andorra"},{value:"Angola"},{value:"Anguilla"},{value:"Antarctica"},{value:"Antigua and Barbuda"},{value:"Argentina"},{value:"Armenia"},{value:"Aruba"},{value:"Australia"},{value:"Austria"},{value:"Azerbaijan"},{value:"Bahamas"},{value:"Bahrain"},{value:"Bangladesh"},{value:"Barbados"},{value:"Belarus"},{value:"Belgium"},{value:"Belize"},{value:"Benin"},{value:"Bermuda"},{value:"Bhutan"},{value:"Bolivia"},{value:"Bosnia and Herzegovina"},{value:"Botswana"},{value:"Bouvet Island"},{value:"Brazil"},{value:"British Indian Ocean Territory"},{value:"Brunei Darussalam"},{value:"Bulgaria"},{value:"Burkina Faso"},{value:"Burundi"},{value:"Cambodia"},{value:"Cameroon"},{value:"Canada"},{value:"Cape Verde"},{value:"Cayman Islands"},{value:"Central African Republic"},{value:"Chad"},{value:"Chile"},{value:"China"},{value:"Christmas Island"},{value:"Cocos (Keeling) Islands"},{value:"Colombia"},{value:"Comoros"},{value:"Congo"},{value:"Congo"},{value:"Cook Islands"},{value:"Costa Rica"},{value:"Cote D'ivoire"},{value:"Croatia"},{value:"Cuba"},{value:"Cyprus"},{value:"Czech Republic"},{value:"Denmark"},{value:"Djibouti"},{value:"Dominica"},{value:"Dominican Republic"},{value:"Ecuador"},{value:"Egypt"},{value:"El Salvador"},{value:"Equatorial Guinea"},{value:"Eritrea"},{value:"Estonia"},{value:"Ethiopia"},{value:"Falkland Islands (Malvinas)"},{value:"Faroe Islands"},{value:"Fiji"},{value:"Finland"},{value:"France"},{value:"French Guiana"},{value:"French Polynesia"},{value:"French Southern Territories"},{value:"Gabon"},{value:"Gambia"},{value:"Georgia"},{value:"Germany"},{value:"Ghana"},{value:"Gibraltar"},{value:"Greece"},{value:"Greenland"},{value:"Grenada"},{value:"Guadeloupe"},{value:"Guam"},{value:"Guatemala"},{value:"Guinea"},{value:"Guinea-bissau"},{value:"Guyana"},{value:"Haiti"},{value:"Heard Island and Mcdonald Islands"},{value:"Holy See (Vatican City State)"},{value:"Honduras"},{value:"Hong Kong"},{value:"Hungary"},{value:"Iceland"},{value:"India"},{value:"Indonesia"},{value:"Iran"},{value:"Iraq"},{value:"Ireland"},{value:"Israel"},{value:"Italy"},{value:"Jamaica"},{value:"Japan"},{value:"Jordan"},{value:"Kazakhstan"},{value:"Kenya"},{value:"Kiribati"},{value:"Korea, (DPR)"},{value:"Korea (Republic)"},{value:"Kuwait"},{value:"Kyrgyzstan"},{value:"Lao People's Democratic Republic"},{value:"Latvia"},{value:"Lebanon"},{value:"Lesotho"},{value:"Liberia"},{value:"Libyan Arab Jamahiriya"},{value:"Liechtenstein"},{value:"Lithuania"},{value:"Luxembourg"},{value:"Macao"},{value:"Macedonia"},{value:"Madagascar"},{value:"Malawi"},{value:"Malaysia"},{value:"Maldives"},{value:"Mali"},{value:"Malta"},{value:"Marshall Islands"},{value:"Martinique"},{value:"Mauritania"},{value:"Mauritius"},{value:"Mayotte"},{value:"Mexico"},{value:"Micronesia"},{value:"Moldova"},{value:"Monaco"},{value:"Mongolia"},{value:"Montserrat"},{value:"Morocco"},{value:"Mozambique"},{value:"Myanmar"},{value:"Namibia"},{value:"Nauru"},{value:"Nepal"},{value:"Netherlands"},{value:"Netherlands Antilles"},{value:"New Caledonia"},{value:"New Zealand"},{value:"Nicaragua"},{value:"Niger"},{value:"Nigeria"},{value:"Niue"},{value:"Norfolk Island"},{value:"Northern Mariana Islands"},{value:"Norway"},{value:"Oman"},{value:"Pakistan"},{value:"Palau"},{value:"Palestinian Territory"},{value:"Panama"},{value:"Papua New Guinea"},{value:"Paraguay"},{value:"Peru"},{value:"Philippines"},{value:"Pitcairn"},{value:"Poland"},{value:"Portugal"},{value:"Puerto Rico"},{value:"Qatar"},{value:"Reunion"},{value:"Romania"},{value:"Russian Federation"},{value:"Rwanda"},{value:"Saint Helena"},{value:"Saint Kitts and Nevis"},{value:"Saint Lucia"},{value:"Saint Pierre and Miquelon"},{value:"Saint Vincent and The Grenadines"},{value:"Samoa"},{value:"San Marino"},{value:"Sao Tome and Principe"},{value:"Saudi Arabia"},{value:"Senegal"},{value:"Serbia and Montenegro"},{value:"Seychelles"},{value:"Sierra Leone"},{value:"Singapore"},{value:"Slovakia"},{value:"Slovenia"},{value:"Solomon Islands"},{value:"Somalia"},{value:"South Africa"},{value:"South Georgia and The South Sandwich Islands"},{value:"Spain"},{value:"Sri Lanka"},{value:"Sudan"},{value:"Suriname"},{value:"Svalbard and Jan Mayen"},{value:"Swaziland"},{value:"Sweden"},{value:"Switzerland"},{value:"Syrian Arab Republic"},{value:"Taiwan"},{value:"Tajikistan"},{value:"Tanzania"},{value:"Thailand"},{value:"Timor-leste"},{value:"Togo"},{value:"Tokelau"},{value:"Tonga"},{value:"Trinidad and Tobago"},{value:"Tunisia"},{value:"Turkey"},{value:"Turkmenistan"},{value:"Turks and Caicos Islands"},{value:"Tuvalu"},{value:"Uganda"},{value:"Ukraine"},{value:"United Arab Emirates"},{value:"United Kingdom"},{value:"United States Minor Outlying Islands"},{value:"Uruguay"},{value:"Uzbekistan"},{value:"Vanuatu"},{value:"Venezuela"},{value:"Vietnam"},{value:"Virgin Islands, British"},{value:"Virgin Islands, U.S."},{value:"Wallis and Futuna"},{value:"Western Sahara"},{value:"Yemen"},{value:"Zambia"},{value:"Zimbabwe"}],countries_abbrev:[{value:"US",label:"United States"},{value:"AF",label:"Afghanistan"},{value:"AL",label:"Albania"},{value:"DZ",label:"Algeria"},{value:"AS",label:"American Samoa"},{value:"AD",label:"Andorra"},{value:"AO",label:"Angola"},{value:"AI",label:"Anguilla"},{value:"AQ",label:"Antarctica"},{value:"AG",label:"Antigua and Barbuda"},{value:"AR",label:"Argentina"},{value:"AM",label:"Armenia"},{value:"AW",label:"Aruba"},{value:"AU",label:"Australia"},{value:"AT",label:"Austria"},{value:"AZ",label:"Azerbaijan"},{value:"BS",label:"Bahamas"},{value:"BH",label:"Bahrain"},{value:"BD",label:"Bangladesh"},{value:"BB",label:"Barbados"},{value:"BY",label:"Belarus"},{value:"BE",label:"Belgium"},{value:"BZ",label:"Belize"},{value:"BJ",label:"Benin"},{value:"BM",label:"Bermuda"},{value:"BT",label:"Bhutan"},{value:"BO",label:"Bolivia"},{value:"BA",label:"Bosnia and Herzegovina"},{value:"BW",label:"Botswana"},{value:"BV",label:"Bouvet Island"},{value:"BR",label:"Brazil"},{value:"IO",label:"British Indian Ocean Territory"},{value:"BN",label:"Brunei Darussalam"},{value:"BG",label:"Bulgaria"},{value:"BF",label:"Burkina Faso"},{value:"BI",label:"Burundi"},{value:"KH",label:"Cambodia"},{value:"CM",label:"Cameroon"},{value:"CA",label:"Canada"},{value:"CV",label:"Cape Verde"},{value:"KY",label:"Cayman Islands"},{value:"CF",label:"Central African Republic"},{value:"TD",label:"Chad"},{value:"CL",label:"Chile"},{value:"CN",label:"China"},{value:"CX",label:"Christmas Island"},{value:"CC",label:"Cocos (Keeling) Islands"},{value:"CO",label:"Colombia"},{value:"CN",label:"Comoros"},{value:"CF",label:"Congo"},{value:"CG",label:"Congo, Democratic Republic of the"},{value:"CW",label:"Cook Islands"},{value:"CS",label:"Costa Rica"},{value:"IV",label:"Cote D'ivoire"},{value:"HR",label:"Croatia"},{value:"CU",label:"Cuba"},{value:"CY",label:"Cyprus"},{value:"EZ",label:"Czech Republic"},{value:"DA",label:"Denmark"},{value:"DJ",label:"Djibouti"},{value:"DO",label:"Dominica"},{value:"DR",label:"Dominican Republic"},{value:"EC",label:"Ecuador"},{value:"EG",label:"Egypt"},{value:"ES",label:"El Salvador"},{value:"EK",label:"Equatorial Guinea"},{value:"ER",label:"Eritrea"},{value:"EN",label:"Estonia"},{value:"ET",label:"Ethiopia"},{value:"FK",label:"Falkland Islands (Malvinas)"},{value:"FO",label:"Faroe Islands"},{value:"FJ",label:"Fiji"},{value:"FI",label:"Finland"},{value:"FR",label:"France"},{value:"FG",label:"French Guiana"},{value:"FP",label:"French Polynesia"},{value:"TF",label:"French Southern Territories"},{value:"GB",label:"Gabon"},{value:"GA",label:"Gambia"},{value:"GG",label:"Georgia"},{value:"GM",label:"Germany"},{value:"GH",label:"Ghana"},{value:"GI",label:"Gibraltar"},{value:"GR",label:"Greece"},{value:"GL",label:"Greenland"},{value:"GJ",label:"Grenada"},{value:"GP",label:"Guadeloupe"},{value:"GQ",label:"Guam"},{value:"GT",label:"Guatemala"},{value:"GV",label:"Guinea"},{value:"PU",label:"Guinea-bissau"},{value:"GY",label:"Guyana"},{value:"HA",label:"Haiti"},{value:"HM",label:"Heard Island and Mcdonald Islands"},{value:"VA",label:"Holy See (Vatican City State)"},{value:"HO",label:"Honduras"},{value:"HK",label:"Hong Kong"},{value:"HU",label:"Hungary"},{value:"IC",label:"Iceland"},{value:"IN",label:"India"},{value:"ID",label:"Indonesia"},{value:"IR",label:"Iran"},{value:"IZ",label:"Iraq"},{value:"EI",label:"Ireland"},{value:"IS",label:"Israel"},{value:"IT",label:"Italy"},{value:"JM",label:"Jamaica"},{value:"JA",label:"Japan"},{value:"JO",label:"Jordan"},{value:"KZ",label:"Kazakhstan"},{value:"KE",label:"Kenya"},{value:"KU",label:"Kiribati"},{value:"KN",label:"Korea, (DPR)"},{value:"KS",label:"Korea (Republic)"},{value:"KU",label:"Kuwait"},{value:"KG",label:"Kyrgyzstan"},{value:"LA",label:"Lao People's Democratic Republic"},{value:"LG",label:"Latvia"},{value:"LE",label:"Lebanon"},{value:"LT",label:"Lesotho"},{value:"LI",label:"Liberia"},{value:"LY",label:"Libyan Arab Jamahiriya"},{value:"LS",label:"Liechtenstein"},{value:"LH",label:"Lithuania"},{value:"LU",label:"Luxembourg"},{value:"MC",label:"Macao"},{value:"MK",label:"Macedonia"},{value:"MA",label:"Madagascar"},{value:"MI",label:"Malawi"},{value:"MY",label:"Malaysia"},{value:"MV",label:"Maldives"},{value:"ML",label:"Mali"},{value:"MT",label:"Malta"},{value:"RM",label:"Marshall Islands"},{value:"MB",label:"Martinique"},{value:"MR",label:"Mauritania"},{value:"MP",label:"Mauritius"},{value:"MF",label:"Mayotte"},{value:"MX",label:"Mexico"},{value:"FM",label:"Micronesia"},{value:"MD",label:"Moldova"},{value:"MN",label:"Monaco"},{value:"MG",label:"Mongolia"},{value:"MS",label:"Montserrat"},{value:"MO",label:"Morocco"},{value:"MZ",label:"Mozambique"},{value:"MM",label:"Myanmar"},{value:"WA",label:"Namibia"},{value:"NR",label:"Nauru"},{value:"NP",label:"Nepal"},{value:"NL",label:"Netherlands"},{value:"NT",label:"Netherlands Antilles"},{value:"NC",label:"New Caledonia"},{value:"NZ",label:"New Zealand"},{value:"NU",label:"Nicaragua"},{value:"NG",label:"Niger"},{value:"NI",label:"Nigeria"},{value:"NE",label:"Niue"},{value:"NF",label:"Norfolk Island"},{value:"CQ",label:"Northern Mariana Islands"},{value:"NO",label:"Norway"},{value:"MU",label:"Oman"},{value:"PK",label:"Pakistan"},{value:"PW",label:"Palau"},{value:"PS",label:"Palestinian Territory"},{value:"PM",label:"Panama"},{value:"PP",label:"Papua New Guinea"},{value:"PA",label:"Paraguay"},{value:"PE",label:"Peru"},{value:"RP",label:"Philippines"},{value:"PC",label:"Pitcairn"},{value:"PL",label:"Poland"},{value:"PO",label:"Portugal"},{value:"RQ",label:"Puerto Rico"},{value:"QA",label:"Qatar"},{value:"RE",label:"Reunion"},{value:"RO",label:"Romania"},{value:"RS",label:"Russian Federation"},{value:"RW",label:"Rwanda"},{value:"SH",label:"Saint Helena"},{value:"SC",label:"Saint Kitts and Nevis"},{value:"ST",label:"Saint Lucia"},{value:"SB",label:"Saint Pierre and Miquelon"},{value:"VC",label:"Saint Vincent and The Grenadines"},{value:"WS",label:"Samoa"},{value:"SM",label:"San Marino"},{value:"TP",label:"Sao Tome and Principe"},{value:"SA",label:"Saudi Arabia"},{value:"SG",label:"Senegal"},{value:"RI",label:"Serbia and Montenegro"},{value:"SE",label:"Seychelles"},{value:"SL",label:"Sierra Leone"},{value:"SN",label:"Singapore"},{value:"LO",label:"Slovakia"},{value:"SI",label:"Slovenia"},{value:"BP",label:"Solomon Islands"},{value:"SO",label:"Somalia"},{value:"SF",label:"South Africa"},{value:"GS",label:"South Georgia and The South Sandwich Islands"},{value:"SP",label:"Spain"},{value:"CE",label:"Sri Lanka"},{value:"SU",label:"Sudan"},{value:"NS",label:"Suriname"},{value:"SV",label:"Svalbard and Jan Mayen"},{value:"WZ",label:"Swaziland"},{value:"SW",label:"Sweden"},{value:"SZ",label:"Switzerland"},{value:"SY",label:"Syrian Arab Republic"},{value:"TW",label:"Taiwan"},{value:"TI",label:"Tajikistan"},{value:"TZ",label:"Tanzania"},{value:"TH",label:"Thailand"},{value:"TT",label:"Timor-leste"},{value:"TO",label:"Togo"},{value:"TL",label:"Tokelau"},{value:"TN",label:"Tonga"},{value:"TD",label:"Trinidad and Tobago"},{value:"TS",label:"Tunisia"},{value:"TU",label:"Turkey"},{value:"TX",label:"Turkmenistan"},{value:"TK",label:"Turks and Caicos Islands"},{value:"TV",label:"Tuvalu"},{value:"UG",label:"Uganda"},{value:"UP",label:"Ukraine"},{value:"AE",label:"United Arab Emirates"},{value:"UK",label:"United Kingdom"},{value:"UM",label:"United States Minor Outlying Islands"},{value:"UY",label:"Uruguay"},{value:"UZ",label:"Uzbekistan"},{value:"NH",label:"Vanuatu"},{value:"VE",label:"Venezuela"},{value:"VM",label:"Vietnam"},{value:"VG",label:"Virgin Islands, British"},{value:"VI",label:"Virgin Islands, U.S."},{value:"WF",label:"Wallis and Futuna"},{value:"EH",label:"Western Sahara"},{value:"YM",label:"Yemen"},{value:"ZA",label:"Zambia"},{value:"ZI",label:"Zimbabwe"}],currencies:[{value:"United States Dollar"},{value:"Euro"},{value:"Pound Sterling"},{value:"Australian Dollar"},{value:"Brazilian Real"},{value:"Argentine Peso"},{value:"Bulgarian Lev"},{value:"Canadian Dollar"},{value:"Chilean Peso"},{value:"Chinese Yuan"},{value:"Colombian Peso"},{value:"Croatian Kuna"},{value:"Czech Koruna"},{value:"Danish Krone"},{value:"Estonian Kroon"},{value:"Honduran Lempira"},{value:"Hong Kong Dollar"},{value:"Hungarian Forint"},{value:"Icelandic Krona"},{value:"Indian Rupee"},{value:"Jamaican Dollar"},{value:"Japanese Yen"},{value:"Korea Won"},{value:"Lithuanian Litas"},{value:"Latvian Lats"},{value:"Malasian Ringgit"},{value:"Mexican Peso"},{value:"Moroccan Dirham"},{value:"New Romanian Leu"},{value:"New Turkish Lira"},{value:"New Zealand Dollar"},{value:"Norwegian Krone"},{value:"Paraguay Guarani"},{value:"Philippine Peso"},{value:"Polish Zloty"},{value:"Qatari Riyal"},{value:"Russian Rouble"},{value:"Salvadoran Colon"},{value:"Saudi Arabian Riyal"},{value:"Singapore Dollar"},{value:"Slovak Koruna"},{value:"South African Rand"},{value:"Sri Lanka Rupee"},{value:"Swedish Krona"},{value:"Swiss Franc"},{value:"Taiwan Dollar"},{value:"Thai Baht"},{value:"Tunisian Dinar"},{value:"Venezuelan Bolivar"}],creditcards:[{value:"Visa"},{value:"MasterCard"},{value:"American Express"},{value:"Discover"}],mapZoomValues:[{value:"13",label:"Default"},{value:"01",label:"1x"},{value:"02",label:"2x"},{value:"03",label:"3x"},{value:"04",label:"4x"},{value:"05",label:"5x"},{value:"06",label:"6x"},{value:"07",label:"7x"},{value:"08",label:"8x"},{value:"09",label:"9x"},{value:"10",label:"10x"},{value:"11",label:"11x"},{value:"12",label:"12x"},{value:"13",label:"13x"},{value:"14",label:"14x"},{value:"15",label:"15x"},{value:"16",label:"16x"}],canada_abbrev:[{value:"AB",label:"Alberta"},{value:"BC",label:"British Columbia"},{value:"MB",label:"Manitoba"},{value:"NB",label:"New Brunswick"},{value:"NL",label:"Newfoundland and Labrador"},{value:"NS",label:"Nova Scotia"},{value:"NT",label:"Northwest Territories"},{value:"NU",label:"Nunavut"},{value:"ON",label:"Ontario"},{value:"PE",label:"Prince Edward Island"},{value:"QC",label:"Quebec"},{value:"SK",label:"Saskatchewan"},{value:"YT",label:"Yukon"}],mapAlignments:[{value:"left",label:"Left"},{value:"center",label:"Center"},{value:"right",label:"Right"}]};
var WebCom_Components_Form_Element_WIDTH={SMALL:"small",MEDIUM:"medium",LARGE:"large",FULL:"full"};
var WebCom_Components_Form_Element_HEIGHT={SMALL:"small",MEDIUM:"medium",LARGE:"large"};
var WebCom_Forms_Beans_Form_Defaults={id:"",name:"",title:"",description:"",elements:[],settings:{},template:""};
function WebCom_Forms_Beans_Form(id,config){jQuery.extend(true,this,{creationTime:new Date()},WebCom_Forms_Beans_Form_Defaults,config);
this.id=id;
for(var i=0;
i<this.elements.length;
i++){this.elements[i]=new WebCom_Components_Form_Element(this.elements[i]);
}this.getElements=function getElements(){return this.elements;
};
this.setElements=function setElements(elements){this.elements=elements;
};
return this;
}var WebCom_Components_Form_Element_Defaults={name:"",label:"",type:WebCom_Components_Form_Element_TYPE.TEXTBOX,isRequired:false,width:WebCom_Components_Form_Element_WIDTH.MEDIUM,height:WebCom_Components_Form_Element_HEIGHT.MEDIUM,defaultValue:"",options:{},validators:[],children:[]};
function WebCom_Components_Form_Element(config){jQuery.extend(true,this,WebCom_Components_Form_Element_Defaults,config);
this.getId=function(){return(this.id!=undefined)?this.id:this.name+"-id";
};
this.clone=function(){var clone=new WebCom_Components_Form_Element(this);
clone.name="rename-me-excl-excl";
clone.id=undefined;
return clone;
};
this.assign=function(config){jQuery.extend(true,this,config);
return this;
};
return this;
}var WebCom_Components_Form_Locale_enus={};
function WebCom_Components_FormElement_getBeforeMarkup(element,renderMode){return'<div class="form-element-wrapper" id="'+element.getId()+'">';
}function WebCom_Components_FormElement_getAfterMarkup(element){return"</div>";
}function WebCom_Components_getInlineStyle(formatting){var inlineStyle="";
if(formatting){var color="";
if(formatting.label){if(formatting.useCustomSize||formatting.useCustomStyle){if(formatting.label.size&&formatting.label.size.length>0){inlineStyle+="font-size:"+formatting.label.size+";";
}}if(formatting.useCustomStyle){color=(formatting.label.color)?formatting.label.color:"";
if(formatting.label.fontWeight&&formatting.label.fontWeight.length>0){inlineStyle+="font-weight:"+formatting.label.fontWeight+";";
}if(formatting.label.fontFace&&formatting.label.fontFace.length>0){inlineStyle+="font-family:"+formatting.label.fontFace+";";
}if(color.length>0){inlineStyle+="color:"+color+";";
}}}}return inlineStyle;
}var WebCom_Components_Form_Template_Element={getWidthSetting:function(element){return"form-element-size-"+element.width.toLowerCase();
},getHeightSetting:function(element){var size={};
size[WebCom_Components_Form_Element_HEIGHT.SMALL]=4;
size[WebCom_Components_Form_Element_HEIGHT.MEDIUM]=8;
size[WebCom_Components_Form_Element_HEIGHT.LARGE]=16;
return size[element.height];
},getSmallerFont:function(size){var smallFont={};
smallFont[WebCom_Components_Form_Element_HEIGHT.SMALL]="x-small";
smallFont[WebCom_Components_Form_Element_HEIGHT.MEDIUM]="small";
smallFont[WebCom_Components_Form_Element_HEIGHT.LARGE]="medium";
return smallFont[size]?smallFont[size]:"smaller";
},getCssClasses:function(element,hasWidth){return"form-element"+(hasWidth?(" "+this.getWidthSetting(element)):"")+(element.css?(" "+element.css):"");
},getOtherFieldInput:function(elementId,suffix){var labelId=elementId?(elementId+suffix):"";
return'<div  id="'+labelId+'" class="other-label"><input id="'+elementId+'" type="text" name="Other-'+elementId+'" class="form-element form-element-other-size" value=""><br><span>Please specify</span></div>';
},getOtherFieldHtml:function(element,isVisible){return'<div id="'+element.name+'-other-label" class=" '+(isVisible?"":"other-label-hidden")+'"  ><br>'+this.getOtherFieldInput(element.name,"-other-label")+"</div>";
},getOptions:function(element){var options=[];
if(element.options.custom&&element.options.custom.length>0){options=options.concat(element.options.custom);
}else{if(element.options.predefined&&element.options.predefined.length>0){options=options.concat(WebCom_Components_Form_Element_OPTION_PREDEFINED[element.options.predefined]);
}}if(element.options.other){options.push({label:"Other",value:"Other"});
}return options;
},getTooltipMarkup:function(element){return(element.toolTip&&element.toolTip.length>0)?'<span id="'+element.name+'-helpIcon" valign="top" class="help_icon">&nbsp;</span><div  id="'+element.name+'-help-text" class="help-text help-text-hidden">'+element.toolTip+"</div>":"";
},getRequiredMarkup:function(element,color){var requiredColor=(color?color:"#cc0000");
return(element.isRequired)?'<span style="color:'+requiredColor+';font-weight:normal" valign="top" >*</span>':"";
},getInlineStyle:function(formatting){return WebCom_Components_getInlineStyle(formatting);
},getLabelMarkup:function(element,formatting){return WebCom.Util.TemplateUtil.format('<label for="${id}" class="${labelClass}" style="${labelStyle}">${label}${required}${helpIcon}</label>',{id:element.name,label:element.label,helpIcon:this.getTooltipMarkup(element),required:this.getRequiredMarkup(element,(formatting.useCustomStyle?formatting.requiredTextColor:null)),labelStyle:this.getInlineStyle(formatting),labelClass:element.labelClass?element.labelClass:"form-element-label"});
},buildHTML:function(element,html,formatting){var label=this.getLabelMarkup(element,formatting);
var pos=WebCom_Components_Form_Element_LABEL_POSITION;
if(element.labelPosition&&(pos.BOTTOM==element.labelPosition||pos.RIGHT==element.labelPosition)){return html+label;
}return label+html;
}};
var WebCom_Components_Form_Template_TextBox_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_Element,{getMarkupText:function(element,formatting){var tpl='<input  class="${classes}" type="text" name="${name}" value="${value}" maxlength="${maxChar}" ${disabled}>';
var html=WebCom.Util.TemplateUtil.format(tpl,{name:element.name,value:element.value||"",maxChar:(element.maxChar)?element.maxChar:"",classes:this.getCssClasses(element,true),disabled:formatting.disabled?"readonly":""});
return this.buildHTML(element,html,formatting);
}});
var WebCom_Components_Form_Template_TextArea_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_Element,{getMarkupText:function(element,formatting){var tpl='<textarea  rows="${height}" class="${classes}" name="${name}" ${disabled}>${value}</textarea>';
var html=WebCom.Util.TemplateUtil.format(tpl,{name:element.name,value:element.value||"",height:this.getHeightSetting(element),classes:this.getCssClasses(element,true),disabled:formatting.disabled?"readonly":""});
return this.buildHTML(element,html,formatting);
}});
var WebCom_Components_Form_Template_Paragraph_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_Element,{getMarkupText:function(element,formatting){var tpl="<span>${value}</span>";
var html=WebCom.Util.TemplateUtil.format(tpl,{value:unescape(element.value)});
return html;
}});
var WebCom_Components_Form_Template_Submit_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_Element,{getTpl:function(){return'<div style="${style}"><input type="submit" class="${classes}" name="${name}" value="${value}" ${disabled}/></div>';
},getStyle:function(element){switch(element.align){default:case"left":return"text-align: left;";
case"center":return"text-align: center;";
case"right":return"text-align: right;";
}},getMarkupText:function(element,formatting){var tpl=this.getTpl();
var html=WebCom.Util.TemplateUtil.format(tpl,{name:element.name,value:element.value,classes:this.getCssClasses(element,false),disabled:formatting.disabled?"disabled":"",style:this.getStyle(element)});
return html;
}});
var WebCom_Components_Form_Template_Checkbox_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_Element,{type:"checkbox",getTemplate:function(){return'<div class="form-option-wrapper"><input id="${id}"  class="${classes}" type="${type}" name="${name}" value="${value}" ${checked} ${disabled}><label for="${id}">${label}</label>${other}</div>';
},isLastElementInRow:function(index,layout){var colLayout=WebCom_Components_Form_Element_LAYOUT;
return(colLayout.ONE_COLUMN==layout)||(colLayout.TWO_COLUMN==layout&&(index%2==0))||(colLayout.THREE_COLUMN==layout&&(index%3==0));
},getLayoutFormat:function(index,layout){if(this.isLastElementInRow(index,layout)){return(this.isTableLayout(layout))?"</tr><tr>":"<br>";
}return"";
},isTableLayout:function(layout){var colLayout=WebCom_Components_Form_Element_LAYOUT;
return(colLayout.ONE_COLUMN==layout||colLayout.TWO_COLUMN==layout||colLayout.THREE_COLUMN==layout);
},getOptionWrapperStyle:function(element){var colLayout=WebCom_Components_Form_Element_LAYOUT;
var width={};
width[colLayout.ONE_COLUMN]="99%";
width[colLayout.TWO_COLUMN]="49%";
width[colLayout.THREE_COLUMN]="33%";
return'style="vertical-align:top;width:'+width[element.fieldLayout]+'"';
},getMarkupText:function(element,formatting){var html="";
var tpl=this.getTemplate();
if(this.isTableLayout(element.fieldLayout)){html+="<table class='"+this.getWidthSetting(element)+"'><tr>";
tpl="<td "+this.getOptionWrapperStyle(element)+">"+tpl+"</td>";
}else{html+="<div class='radiocheckbox-wrapper-"+this.getWidthSetting(element)+"'>";
}var options=this.getOptions(element);
for(var i=0;
i<options.length;
i++){var option=options[i];
var value=option.value;
if(value&&value.length>0){var label=option.label||option.value;
html+=WebCom.Util.TemplateUtil.format(tpl,{value:value,type:this.type,id:element.name+"_"+i,name:element.name,label:(value=="Other")?label+": ":label,other:(value=="Other")?this.getOtherFieldInput(element.name,"-other-label-tooltip"):"",checked:(element.value==value)?"checked":"",classes:this.getCssClasses(element,false),disabled:formatting.disabled?"readonly":""});
html+=this.getLayoutFormat((i+1),element.fieldLayout);
}}if(this.isTableLayout(element.fieldLayout)){html+="</tr></table>";
}else{html+="</div>";
}html+='<div class="form-option-closer"></div>';
return this.buildHTML(element,html,formatting);
}});
var WebCom_Components_Form_Template_RadioButton_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_Checkbox_Edit,{type:"radio"});
var WebCom_Components_Form_Template_DropDown_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_Element,{getSize:function(){return"";
},getAttributes:function(){return"";
},isSelected:function(element,value){return(element.value&&element.value==value);
},getOptionsHtml:function(element){var options=this.getOptions(element);
var optionsHtml="";
var optionTpl='<option value="${value}" ${selected}>${label}<br>';
if(element.value=="PredefinedDefaultValueNone"){optionsHtml+=WebCom.Util.TemplateUtil.format(optionTpl,{value:"",label:"Select...",selected:"selected"});
}for(var i=0;
i<options.length;
i++){var option=options[i];
var value=option.value;
var label=option.label||option.value;
optionsHtml+=WebCom.Util.TemplateUtil.format(optionTpl,{value:value,label:label,selected:this.isSelected(element,value)?"selected":""});
}return optionsHtml;
},getMarkupText:function(element,formatting){var outerTpl='<select ${size} ${attributes} class="${classes}" name="${name}" ${disabled}>${options}</select>';
var optionsHtml=this.getOptionsHtml(element);
var html=WebCom.Util.TemplateUtil.format(outerTpl,{name:element.name,options:optionsHtml,size:this.getSize(element),attributes:this.getAttributes(),classes:this.getCssClasses(element,true),disabled:formatting.disabled?"readonly":""});
if(element.options&&element.options.other){html+=this.getOtherFieldHtml(element,false);
}return this.buildHTML(element,html,formatting);
}});
var WebCom_Components_Form_Template_MultiSelect_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_DropDown_Edit,{getSize:function(element){return'size="'+this.getHeightSetting(element)+'"';
},getAttributes:function(){return"multiple";
},isSelected:function(element,value){if(element.value){var multipleValues=element.value.split(",");
for(var i=0;
i<multipleValues.length;
i++){if(multipleValues[i]==value){return true;
}}}return false;
}});
var WebCom_Components_Form_Template_Email_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_TextBox_Edit);
var WebCom_Components_Form_Template_PersonName_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_Element,{getRequiredMarkup:function(element,color){if(element.type==WebCom_Components_Form_Element_TYPE.PERSON_NAME){return"";
}var requiredColor=(color?color:"#cc0000");
return(element.isRequired)?'<span style="color:'+requiredColor+';font-weight:normal" valign="top" >*</span>':"";
},getPersonNameClass:function(element){var w=element.width.toLowerCase();
var className="personName-"+w;
if(webcom.util.isIE){var hasFN=false,hasLN=false,hasMI=false,hasS=false;
for(var i=0;
i<element.children.length;
i++){if(/FirstName/i.test(element.children[i].name)){hasFN=true;
}else{if(/LastName/i.test(element.children[i].name)){hasLN=true;
}else{if(/MiddleInitial/i.test(element.children[i].name)){hasMI=true;
}else{if(/Suffix/i.test(element.children[i].name)){hasS=true;
}}}}}if(hasFN&&hasLN){if(hasMI&&!hasS){className+="-fnmiln";
}if(!hasMI&&hasS){className+="-fnlns";
}if(!hasMI&&!hasS){className+="-fnln";
}}}return className;
},getMarkupText:function(element,formatting){var html='<table class="'+this.getPersonNameClass(element)+'" cellpadding="0" cellspacing="0"><tr>';
if(element.children){var subOptionFormatting=jQuery.extend(true,{},formatting);
if(formatting.label){var label=jQuery.extend(true,{},formatting.label);
label.size=this.getSmallerFont(label.size);
subOptionFormatting.useCustomSize=true;
subOptionFormatting.label=label;
}for(var i=0;
i<element.children.length;
i++){var child=jQuery.extend(true,{},element.children[i]);
html+='<td class="'+child.name+'">';
child.name=element.name+"-"+child.name;
child.labelPosition=WebCom_Components_Form_Element_LABEL_POSITION.BOTTOM;
child.labelClass="personName-label";
child.width=WebCom_Components_Form_Element_WIDTH.FULL;
html+=WebCom_Forms_Builder_FormElementGenerator.getHTML(child,formatting.renderMode,true,subOptionFormatting);
html+="</td>";
}}html+="</tr></table>";
return this.buildHTML(element,html,formatting);
}});
var WebCom_Components_Form_Template_Address_Edit=jQuery.extend(true,{},WebCom_Components_Form_Template_Element,{getRequiredMarkup:function(element,color){if(element.type==WebCom_Components_Form_Element_TYPE.ADDRESS){return"";
}var requiredColor=(color?color:"#cc0000");
return(element.isRequired)?'<span style="color:'+requiredColor+';font-weight:normal" valign="top" >*</span>':"";
},getUSMarkup:function(width){return"<table cellpadding='0' cellspacing='0' class='address-"+width+"'><tr><td class='addressLine' colspan='3'>${AddressLine1}</td></tr><tr><td class='addressLine' colspan='3'>${AddressLine2}</td></tr><tr><td class='city'>${City}</td><td class='state'>${State}</td><td class='zip'>${Zip}</td></tr></table>";
},getIntlMarkup:function(width){return"<table cellpadding='0' cellspacing='0' class='address-"+width+"'><tr><td class='addressLine' colspan='2'>${AddressLine1}</td></tr><tr><td class='addressLine' colspan='2'>${AddressLine2}</td></tr><tr><td class='city'>${City}</td><td class='stateIntl'>${State}</td></tr><tr><td class='postal'>${Postal}</td><td class='country'>${Country}</td></tr></table>";
},getMarkupText:function(element,formatting){var html="",tpl="";
if(!element.schema){WebCom_Components_Form_Element_updateToUSAddress(element);
}if(WebCom_Components_Form_Element_SCHEMA.US==element.schema){tpl=this.getUSMarkup(element.width.toLowerCase());
}else{tpl=this.getIntlMarkup(element.width.toLowerCase());
}var tplHash={};
if(element.children){var subOptionFormatting=jQuery.extend(true,{},formatting);
if(formatting.label){var label=jQuery.extend(true,{},formatting.label);
label.size=this.getSmallerFont(label.size);
subOptionFormatting.label=label;
subOptionFormatting.useCustomSize=true;
}for(var i=0;
i<element.children.length;
i++){var child=jQuery.extend(true,{},element.children[i]);
if(child.label=="State/Province/Region"&&(element.width==WebCom_Components_Form_Element_WIDTH.SMALL||element.width==WebCom_Components_Form_Element_WIDTH.MEDIUM)){child.label="State";
}child.name=element.name+"-"+child.name;
child.labelClass="address-label";
child.labelPosition=WebCom_Components_Form_Element_LABEL_POSITION.BOTTOM;
child.width=WebCom_Components_Form_Element_WIDTH.FULL;
tplHash[element.children[i].name]=WebCom_Forms_Builder_FormElementGenerator.getHTML(child,formatting.renderMode,true,subOptionFormatting);
}html=WebCom.Util.TemplateUtil.format(tpl,tplHash);
}return this.buildHTML(element,html,formatting);
}});
function WebCom_Components_Form_PostSubmission_Display(component,msgKey,defaultMsg,className){var result="",msg="";
try{if(component.form.settings&&component.form.settings.postSubmission){msg=component.form.settings.postSubmission[msgKey];
}if(/string/i.test(typeof(msg))){result=msg;
}else{result=msg.value;
if(!result||(!/string/i.test(typeof(result)))||result.length==0){result=defaultMsg;
}}}catch(e1){result=defaultMsg;
}var styleValue="",c="";
if(component.form.settings.formatting.useCustomStyle){try{if(/errorValue/i.test(msgKey)){c=component.form.settings.formatting.errorMsgColor;
}else{c=component.form.settings.formatting.postSubmissionMsgColor;
}}catch(e2){}if(c&&c.length>0){styleValue="color:"+c+'";';
}}var alignment=component.form.settings.formatting.formAlignment;
if(alignment==undefined||alignment.length==0){alignment="center";
}styleValue=styleValue+"text-align: "+alignment+";";
return'<div class="'+className+'" style="'+styleValue+'">'+result+"</div>";
}var WebCom_Components_Form_Template_MasterTemplate_Ok={getMarkupText:function(component,formatting){return WebCom_Components_Form_PostSubmission_Display(component,"message","Submisssion completed","form-result-ok");
}};
var WebCom_Components_Form_Template_MasterTemplate_Err={getMarkupText:function(component,formatting){return WebCom_Components_Form_PostSubmission_Display(component,"errorValue","Submisssion failed","form-result-err");
}};
var WebCom_Components_Form_Template_MasterTemplate_Builder={getMarkupText:function(component){return WebCom_Forms_Builder_FormGenerator.getHTML(component.getForm(),"Builder");
}};
var WebCom_Components_Form_Template_MasterTemplate_Edit={getMarkupText:function(component){return WebCom_Forms_Builder_FormGenerator.getHTML(component.getForm(),"Edit");
}};
var WebCom_Components_Form_Template_MasterTemplate_Preview={getMarkupText:function(component){return WebCom_Forms_Builder_FormGenerator.getHTML(component.getForm(),"Preview");
}};
var WebCom_Components_Form_Template_MasterTemplate_Publish={getMarkupText:function(component){return WebCom_Forms_Builder_FormGenerator.getHTML(component.getForm(),"Publish");
}};
var WebCom_Components_Form_Template_Title_Edit={getText:function(element,formatting){return element.name;
},getMarkupText:function(element,formatting){var tpl="<div id='${id}-form-title' class='form-element-wrapper form-name'>${name}</div>";
var html=WebCom.Util.TemplateUtil.format(tpl,{id:element.id,name:element.name});
return html;
}};
var WebCom_Forms_Builder_FormGenerator={getFormHTML:function(settings,renderMode){var html='<form id="${id}-form" class="web_com_custom_form" method="post" action="${actionUrl}" onSubmit="${onSubmit}" >\n';
var validationStyle="",validationStyleElement="";
if(settings&&settings.formatting&&settings.formatting.errorMsgColor){validationStyle='style="color:'+settings.formatting.errorMsgColor+'"';
validationStyleElement="<style>#${id} div.form_error{ color: "+settings.formatting.errorMsgColor+";}\n#${id} input.form_error,#${id} textarea.form_error{border:1px dotted "+settings.formatting.errorMsgColor+" !important; }</style>";
}html+=validationStyleElement;
html+="${body} \n";
html+="</form>";
return html;
},doAlignment:function(alignType,renderMode,innerHTML){var html="";
if(renderMode!="Builder"){switch(alignType){default:case"center":html+='<table cellspacing="0" cellpadding="0" border="0" width="100%"> <tr> <td align="left" valign="top" width="45%">&nbsp;</td> <td align="left" valign="top" width="10%">';
break;
case"left":break;
case"right":html+='<table cellspacing="0" cellpadding="0" border="0" width="100%"> <tr> <td align="left" valign="top" width="90%">&nbsp;</td> <td align="left" valign="top" width="10%">';
break;
}}html+=innerHTML;
if(renderMode!="Builder"){switch(alignType){default:case"center":html+='</td> <td align="left" valign="top" width="45%">&nbsp;</td> </tr> </table>';
break;
case"left":break;
case"right":html+="</td> </tr> </table>";
break;
}}return html;
},getHTML:function(form,renderMode){var html="";
var formHtml=this.getFormHTML(form.settings,renderMode);
var alignment=form.settings.formatting.useCustomStyle?form.settings.formatting.formAlignment:"center";
formHtml=this.doAlignment(alignment,renderMode,formHtml);
if(renderMode=="Builder"){renderMode="Edit";
}formHtml=WebCom.Util.TemplateUtil.format(formHtml,{id:form.id,actionUrl:(/edit/i.test(renderMode))?"#":form.formProcessorUrl,onSubmit:(/edit/i.test(renderMode))?"return false":"return WebCom.Components.Form.submitInstance(this)"});
var elements=form.getElements(form,renderMode);
for(var i=0;
i<elements.length;
i++){html+=WebCom_Forms_Builder_FormElementGenerator.getHTML(elements[i],renderMode,false,form.settings.formatting);
}formHtml=formHtml.replace("${body}",html);
return formHtml;
}};
var WebCom_Forms_Builder_FormElementGenerator={getFormTitleSpec:function(form){return{tag:"div",id:form.id+"",cls:"form-element-wrapper",style:WebCom_Components_getInlineStyle(form.settings.formatting),html:WebCom_Components_Form_Template_Title_Edit.getText(form,form.settings.formatting)};
},getHTMLSpec:function(element,renderMode,formatting){var html=this.getHTML(element,renderMode,true,formatting);
return{tag:"div",id:element.id,cls:"form-element-wrapper",html:html};
},getHTML:function(element,renderMode,bodyOnly,formatting){var html=bodyOnly?"":WebCom_Components_FormElement_getBeforeMarkup(element,renderMode);
var elemFormatting=jQuery.extend(true,{},formatting);
elemFormatting.renderMode=renderMode;
if(renderMode=="Edit"){elemFormatting.disabled=true;
}var funcName="WebCom_Components_Form_Template_"+element.type+"_Edit";
eval("html += "+funcName+".getMarkupText(element, elemFormatting);");
html+=bodyOnly?"":WebCom_Components_FormElement_getAfterMarkup(element);
return html;
}};
(function(){var VERSION="1.0";
var NAME="com.web.components.form";
var scripts=["js/utils.js","js/resources.js","js/templates.js"];
var styles=["css/form.css"];
var lib=new webcom.library("WebCom.Components.Form",NAME,VERSION,scripts,styles);
function WebCom_Components_Form(){WebCom.Components.Component.apply(this,[lib]);
var SERVICE_ENDPOINT_URL="http://forms.services.matrixbuilder.com/forms/processor.sfx";
var SERVICE_SECURE_ENDPOINT_URL="https://forms-services.matrixbuilder.com/forms/processor.sfx";
var self=this;
if(typeof LIGHTING_ONE_SERVICE_ENDPOINT_URL!=="undefined"){SERVICE_ENDPOINT_URL=LIGHTING_ONE_SERVICE_ENDPOINT_URL;
}if(typeof LIGHTING_ONE_SERVICE_SECURE_ENDPOINT_URL!=="undefined"){SERVICE_SECURE_ENDPOINT_URL=LIGHTING_ONE_SERVICE_SECURE_ENDPOINT_URL;
}this.init=function(id,config,extraConfig){if(extraConfig&&extraConfig.serviceEndPointURL){SERVICE_ENDPOINT_URL=extraConfig.serviceEndPointURL;
}if(extraConfig&&extraConfig.serviceSecureEndPointURL){SERVICE_SECURE_ENDPOINT_URL=extraConfig.serviceSecureEndPointURL;
}this.id=id;
this.q=config.miscData.q;
this.encType=config.miscData.encType;
this.renderMode=config.miscData.renderMode;
if(/Publish/i.test(this.renderMode)){config.componentData.form.formProcessorUrl=(config.componentData.form&&config.componentData.form.settings&&config.componentData.form.settings.isSecure)?SERVICE_SECURE_ENDPOINT_URL:SERVICE_ENDPOINT_URL;
}else{config.componentData.form.formProcessorUrl="#";
}this.form=new WebCom_Forms_Beans_Form(id,config.componentData.form);
};
this.getForm=function(){return this.form;
};
this.getHTML=function(){var tpl=this.getMasterTemplate("Builder");
return tpl.getMarkupText(this);
};
this.getFormElementHTML=function(element,mode){return WebCom_Forms_Builder_FormElementGenerator.getHTML(element,mode);
};
this.getMasterTemplate=function(mode){return this.getTemplate("MasterTemplate",mode,this.layoutName);
};
this.getFormattingValues=function(mode){var formattingValues={};
this.getLocalization(this.locale,formattingValues);
return formattingValues;
};
this.getRuleForElement=function(element){var rule={};
rule.required=(element.isRequired);
if(element.type==WebCom_Components_Form_Element_TYPE.RADIOBUTTON||element.type==WebCom_Components_Form_Element_TYPE.CHECKBOX){rule.minlength=1;
}var validators=element.validators;
if(validators&&validators.length>0){for(var j=0;
j<validators.length;
j++){var validator=validators[j];
var type=validator.type;
if(type){if(/length/i.test(type)){rule.rangelength=[validator.config.min,validator.config.max];
if(element.type==WebCom_Components_Form_Element_TYPE.TEXTAREA){rule.onkeyup=true;
}}else{if(/email/i.test(type)){rule.email=true;
}else{if(/range/i.test(type)){rule.range=[validator.config.low,validator.config.high];
}}}}}}if(element.maxChar){rule.rangelength=[0,element.maxChar];
}return rule;
};
this.getElementValidationOption=function(element,prefix){var rules={};
var name=element.name;
if(prefix&&prefix.length>0){name=prefix+"-"+element.name;
}if(element.children&&element.children.length>0){for(var i=0;
i<element.children.length;
i++){jQuery.extend(rules,this.getElementValidationOption(element.children[i],name));
}}else{rules[name]=this.getRuleForElement(element);
if(element.type==WebCom_Components_Form_Element_TYPE.TEXTAREA&&rules[name]["rangelength"]){this.textAreasToValidate.push({name:element.name,maxLength:element.maxChar});
}}return rules;
};
this.getValidationOptions=function(){var elements=this.getForm().getElements();
var rules={},newRules;
for(var i=0;
i<elements.length;
i++){newRules=this.getElementValidationOption(elements[i]);
jQuery.extend(rules,newRules);
}return rules;
};
this.getMessagesForElement=function(element){var messages={};
if(element.isRequired){messages.required=element.label+" is a required field.";
}var validators=element.validators;
if(validators&&validators.length>0){for(var j=0;
j<validators.length;
j++){var validator=validators[j];
var type=validator.type;
if(type){if(/length/i.test(type)){messages.rangelength=element.label+" has to be between "+validator.config.min+" and "+validator.config.max+" characters.";
}else{if(/email/i.test(type)){messages.email=element.label+" has to be a valid email address.";
}else{if(/range/i.test(type)){rule.range=element.label+" has to be between "+validator.config.low+" and "+validator.config.high+".";
}}}}}}if(element.maxChar){messages.rangelength=element.label+" cannot be more than "+element.maxChar+" characters.";
messages.maxlength=element.label+" cannot be more than "+element.maxChar+" characters.";
}return messages;
};
this.getElementValidationMessages=function(element,prefix){var messages={};
var name=element.name;
if(prefix&&prefix.length>0){name=prefix+"-"+element.name;
}if(element.children&&element.children.length>0){for(var i=0;
i<element.children.length;
i++){jQuery.extend(messages,this.getElementValidationMessages(element.children[i],name));
}}else{messages[name]=this.getMessagesForElement(element);
}return messages;
};
this.getValidationMessages=function(){var elements=this.getForm().getElements();
var messages={},newMessages;
for(var i=0;
i<elements.length;
i++){newMessages=this.getElementValidationMessages(elements[i]);
jQuery.extend(messages,newMessages);
}return messages;
};
return this;
}WebCom_Components_Form.prototype=new WebCom.Components.Component();
WebCom.Components.Form={instances:[],renderInstances:function(instances,globalSettings,extraConfig){var url=document.location+"";
var submissionFormId="";
var submissionResult="";
if(/\#(.*)\?(.*)/.test(url)){submissionFormId=RegExp.$1;
submissionResult=RegExp.$2;
}else{if(/(.*)\?Err(.*)/.test(url)){submissionFormId=instances[0].id;
submissionResult="Err";
}}for(var i=0;
i<instances.length;
i++){var inst=instances[i];
if(globalSettings&&globalSettings.listeners){if(inst.listeners==null){inst.listeners=globalSettings.listeners;
}else{var listeners=inst.listeners;
for(var eventName in globalSettings.listeners){if(listeners[eventName]==null){listeners[eventName]=globalSettings.listeners[listenerName];
}}}}var comp=new WebCom_Components_Form();
comp.init(inst.id,inst,extraConfig);
var result="";
if(submissionFormId==inst.id){comp.renderMode=submissionResult;
}comp.isFirstSubmission=true;
comp.render(comp.renderMode,null);
this.postRender(comp);
this.instances[inst.id]=comp;
}},setupTooltips:function(formId){function positionTooltip(elem){var label=jQuery(elem);
var offset=label.offset();
jQuery(formId+" div#"+elem.id.replace("-helpIcon","")+"-help-text").css({left:(offset.left+label.width()+17)+"px",top:(offset.top+label.height()+5)+"px"});
}jQuery(formId+" span[id$='-helpIcon']").mouseover(function(){jQuery(formId+" div#"+this.id.replace("-helpIcon","")+"-help-text").removeClass("help-text-hidden");
positionTooltip(this);
}).mouseout(function(){jQuery(formId+" div#"+this.id.replace("-helpIcon","")+"-help-text").addClass("help-text-hidden");
});
},enableOtherField:function(enable,label){if(enable){jQuery(label).removeClass("other-label-hidden");
}else{jQuery(label).addClass("other-label-hidden");
}},setupOtherFields:function(formId){var self=this;
jQuery(formId+" div[id$='-other-label-tooltip']").each(function(){var label=jQuery(this);
var prevElem=label.prev();
label.css({top:"-"+prevElem.height()+"px",left:(prevElem.width()+10)+"px"});
});
jQuery(formId+" div[id$='-other-label']").each(function(){var label=this;
var id=this.id.replace("-other-label","");
jQuery(formId+" select[name='"+id+"']").click(function(){var s=jQuery(this);
var isOtherEnabled=(s.attr("multiple"))?(/other/i.test(s.val())):(s.val()=="Other");
var isOtherDisabled=!isOtherEnabled;
if(isOtherEnabled||isOtherDisabled){self.enableOtherField(isOtherEnabled,label);
}});
});
jQuery(formId+" div[id$='-other-label-tooltip']").each(function(){var id=this.id.replace("-other-label-tooltip","");
jQuery(formId+" input[name='Other-"+id+"']").focus(function(){var id=this.id.replace("Other-","");
var elem=jQuery("input[name='"+id+"']");
elem.each(function(){if(this.value=="Other"){this.checked=true;
}});
});
});
},enableTextAreaMaxLength:function(formId,v,name,maxLength){jQuery(formId+" textarea[name='"+name+"']").keyup(function(event){var isValid=v.element(this);
if(!isValid){jQuery(this).addClass("form_error");
}else{jQuery(this).removeClass("form_error");
}});
},postRender:function(comp){var formSelector="#"+comp.id+" form";
this.setupTooltips(formSelector);
this.setupOtherFields(formSelector);
comp.textAreasToValidate=new Array();
var v=jQuery(formSelector).validate({errorClass:"form_error",errorElement:"div",onfocusout:false,onkeyup:false,focusCleanup:true,rules:comp.getValidationOptions(),messages:comp.getValidationMessages(),focusInvalid:false,errorPlacement:function(error,element){if(/radio/i.test(element.attr("type"))||/checkbox/i.test(element.attr("type"))){error.insertAfter("#"+element.attr("name")+"-id table");
}else{error.insertAfter(element);
}}});
if(comp.textAreasToValidate.length>0){for(var i=0;
i<comp.textAreasToValidate.length;
i++){this.enableTextAreaMaxLength(formSelector,v,comp.textAreasToValidate[i].name,comp.textAreasToValidate[i].maxLength);
}}},getInstance:function(id,config){var comp=new WebCom_Components_Form();
comp.init(id,config);
return comp;
},createHiddenParam:function(form,name,value){var qNode=document.createElement("input");
qNode.setAttribute("type","hidden");
qNode.setAttribute("name",name);
qNode.value=value;
form.appendChild(qNode);
},submitInstance:function(form){var compId=form.id.substring(0,form.id.length-5);
var comp=this.instances[compId];
if(comp.isFirstSubmission){this.createHiddenParam(form,"q",comp.q);
var returnUrl=document.location+"";
var a=returnUrl.indexOf("#");
if(a!=-1){returnUrl=returnUrl.substr(0,a);
}this.createHiddenParam(form,"returnUrl",returnUrl);
this.createHiddenParam(form,"formId",compId);
comp.isFirstSubmission=false;
}return true;
}};
})();
var FormPlugin={name:"FormPlugin",cssClass:"form-plugin",template:$("#form-plugin-inner").html(),enableElement:function($el){try{var pluginConfigStr=$el.attr("data-plugin-config");
var pluginConfig=JSON.parse(pluginConfigStr);
if((typeof builderSettings=="undefined"||!builderSettings.isBuilder)&&(pluginConfig.id.trim()==""||pluginConfig.id.trim()=="preview_id_only")){pluginConfig.id="preview_id_only";
}}catch(e){if(typeof console!="undefined"){console.error("FormPlugin enableElement",e.message);
}return;
}if(typeof console!="undefined"){console.log("FormPlugin enableElement pluginConfig",pluginConfig);
}$el.attr({"data-ng-controller":"FormPluginController","data-ng-click":"select();","data-module-class":"FormModule"});
if(!pluginConfig.id){pluginConfig.componentData.form.settings.formId=+new Date();
pluginConfig.componentData.form.creationTime=new Date().toISOString();
if(typeof(FormModule)!="undefined"){pluginConfig.componentData.form.siteId=webcom.common.SiteService.getActiveSiteId();
pluginConfig.componentData.form.pageId=webcom.common.SiteService.getActivePageId();
}else{pluginConfig.componentData.form.siteId=0;
pluginConfig.componentData.form.pageId=0;
}FormPlugin.hashForm(pluginConfig,$el,true);
}else{FormPlugin.parseTemplate($el,pluginConfig);
FormPlugin.renderForm(pluginConfig);
}var submit=$(".web_com_custom_form").find(":submit");
if(typeof submit!="undefined"&&!$("body").hasClass("neo-publish")){submit.attr("disabled","disabled");
}$el.css("background-image","none");
neo.Plugin.bootstrap($el);
},hashForm:function(formInfo,el,ngBootstrap){return $.ajax({method:"POST",contentType:"application/json",dataType:"json",url:"/neo/form/create",data:JSON.stringify(formInfo)}).success(function(response){if(response){var configObj=response;
if(!configObj.error){el.attr("data-plugin-config",JSON.stringify(configObj));
FormPlugin.parseTemplate(el,configObj);
FormPlugin.renderForm(configObj);
neo.savePage(null,null,true);
if(ngBootstrap){neo.Plugin.bootstrap(el);
}}}}).error(function(request,status,error){neo.GenericModal.pop("ERROR",request.responseJSON.error);
});
},updateForm:function(formConfig,el,ngBootstrap){return $.ajax({method:"POST",contentType:"application/json",dataType:"json",url:"/neo/form/update",data:JSON.stringify(formConfig)}).success(function(response){if(response){var configObj=response;
if(!configObj.error){el.attr("data-plugin-config",JSON.stringify(configObj));
FormPlugin.parseTemplate(el,configObj);
FormPlugin.renderForm(configObj);
if(ngBootstrap){neo.Plugin.bootstrap($el);
}}}}).error(function(request,status,error){neo.GenericModal.pop("ERROR",request.responseJSON.error);
});
},parseTemplate:function($el,config){var templateMods;
if((typeof builderSettings=="undefined"||!builderSettings.isBuilder)&&(config.id.trim()==""||config.id.trim()=="preview_id_only")){templateMods='<div class="form-ng remove-on-save"><div id="preview_id_only">inject webcom-forms here</div></div>';
}else{templateMods=FormPlugin.template.replace("{{FormId}}",config.id);
}$el.find(".neo-asset-inner").html(templateMods);
$el.attr({"data-ng-controller":"FormPluginController","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit()"});
if(typeof(FormModule)!="undefined"){neo.PropertiesNgModule.clickCloak.addClickCloak($el);
}},renderForm:function(pluginConfig){WebCom.Components.Form.renderInstances([pluginConfig]);
},enableAllElements:function(){$(".form-plugin").each(function(){FormPlugin.enableElement($(this));
});
},ngPluginController:function($scope,$rootScope,$element){$scope.select=function(){if(typeof(FormModule)=="object"){FormModule.select($element);
}};
$scope.selectAndEdit=function(){if(typeof(FormModule)=="object"){var $ppScope=$("#properties-module-shell").scope();
if(!$("#properties-module-shell").hasClass("active")){FormModule.select($element);
}$ppScope.onSwapPropertyPanel();
}};
},manageFormSubmission:function(){$.ajax({method:"POST",url:"/neo/form/manage"}).success(function(response){var newWin=window.open(response,"MessageAdministration","width=750,height=625,location=0,menubar=0,resizable=1,scrollbars=1,status=0,toolbar=0");
newWin.focus();
}).error(function(request,status,error){if(typeof console!="undefined"){console.error("Form Submission manager error occured:",error);
}});
}};
webcomApp.controller("FormPluginController",FormPlugin.ngPluginController);
webcomApp.registerPlugin(FormPlugin);
neo.BoxPlugin=neo.Plugin.extend({id:"Box",});
neo.ImagePlugin=neo.Plugin.extend({id:"Image"});
ImagePlugin=neo.ImagePlugin;
neo.TextPlugin=neo.Plugin.extend({id:"Text",postBootstrap:function($el){var moduleClassString=$el.attr("data-module-class");
var moduleClass=null;
try{if(moduleClassString){moduleClass=eval(moduleClassString);
}}catch(e){}if(typeof(moduleClass)=="object"){neo.PropertiesNgModule.clickCloak.addClickCloak($el);
}},enableElement:function($el){var t=this;
webcomApp.controller("TextPluginController",function($scope,$rootScope,$element,$compile,$timeout){var moduleClassString=$el.attr("data-module-class");
var moduleClass=null;
try{if(moduleClassString){moduleClass=eval(moduleClassString);
}}catch(e){}$scope.select=function(){if(typeof(moduleClass)=="object"){moduleClass.select($element);
}};
$scope.selectAndEdit=function(){if(typeof(moduleClass)=="object"){var $ppScope=$("#properties-module-shell").scope();
if(!$("#properties-module-shell").hasClass("active")){moduleClass.select($element);
}$ppScope.onSwapPropertyPanel();
}};
});
$el.attr({"data-ng-controller":t.name+"Controller","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit();","data-module-class":t.moduleClass});
neo.Plugin.bootstrap($el);
t.postBootstrap($el);
},});
neo.NavigationPlugin=neo.Plugin.extend({id:"Navigation",cssClass:"navigation-plugin",init:function(){if(!builderSettings.isBuilder){$(function(){neo.NavigationPlugin.selectActivePage();
});
}},enableElement:function($el){if(typeof(neo.NavigationModule)!="undefined"){neo.NavigationModule.populateNavigation($el);
neo.PropertiesNgModule.clickCloak.addClickCloak($el);
$(".neo-navigation-menu",$el).attr({"data-k-on-open":"onKendoMenuOpen(kendoEvent)","data-k-on-select":"onKendoMenuSelect(kendoEvent)"});
}$el.attr({"data-module-class":this.moduleClass});
var navOptions={};
var navUlArr=$el.find(".neo-asset-inner>ul");
var navUl=navUlArr.length>0?navUlArr[0]:null;
if(navUl&&$(navUl).attr("data-k-orientation")&&$(navUl).attr("data-k-orientation")=="'vertical'"){navOptions.orientation="vertical";
}$(navUl).kendoMenu(navOptions);
neo.NavigationPlugin.selectActivePage($el);
neo.Plugin.bootstrap($el);
},selectActivePage:function($el){var fileName="index.html";
if(builderSettings.isBuilder){var activePage=webcom.common.SiteService.getActivePage();
if(activePage){fileName=activePage.fileName;
}}else{var index=document.URL.lastIndexOf("/")+1;
fileName=document.URL.substr(index).toLowerCase();
fileName=((fileName.indexOf("?")>=0)?fileName.substr(0,fileName.indexOf("?")):fileName)||"index.html";
}if(typeof $el=="undefined"){$el=$(".navigation-plugin");
}$el.find("li a").each(function(){var linkHref=$(this).attr("href").toLowerCase();
if(linkHref==fileName){$(this).parent().addClass("k-state-active").addClass("selected-page").addClass("k-state-highlight");
}else{$(this).parent().removeClass("k-state-active").removeClass("selected-page").removeClass("k-state-highlight");
}});
},ngPluginController:function($scope,$rootScope,$element){$scope.select=function(){if(typeof(neo.NavigationModule)=="object"){neo.NavigationModule.select($element);
}};
$scope.onKendoMenuOpen=function(e){if(typeof neo.NavigationModule!="undefined"){e.preventDefault();
}};
$scope.onKendoMenuSelect=function(e){if(typeof neo.NavigationModule!="undefined"){e.preventDefault();
}};
}});
neo.Navigation2Plugin=neo.Plugin.extend({id:"Navigation2",cssClass:"navigation-2-plugin",init:function(){if(!builderSettings.isBuilder){$(function(){neo.Navigation2Plugin.selectActivePage();
});
}},enableElement:function($el){if(typeof(neo.Navigation2Module)!="undefined"){neo.Navigation2Module.populateNavigation($el);
neo.PropertiesNgModule.clickCloak.addClickCloak($el);
$(".neo-navigation-menu",$el).attr({"data-k-on-open":"onKendoMenuOpen(kendoEvent)","data-k-on-select":"onKendoMenuSelect(kendoEvent)"});
}$el.attr({"data-module-class":this.moduleClass});
var navOptions={};
var navUlArr=$el.find(".neo-asset-inner>ul");
var navUl=navUlArr.length>0?navUlArr[0]:null;
if(navUl&&$(navUl).attr("data-k-orientation")&&$(navUl).attr("data-k-orientation")=="'vertical'"){navOptions.orientation="vertical";
}$(navUl).kendoMenu(navOptions);
neo.Navigation2Plugin.selectActivePage($el);
neo.Plugin.bootstrap($el);
},selectActivePage:function($el){var fileName="index.html";
if(builderSettings.isBuilder){var activePage=webcom.common.SiteService.getActivePage();
if(activePage){fileName=activePage.fileName;
}}else{var index=document.URL.lastIndexOf("/")+1;
fileName=document.URL.substr(index).toLowerCase();
fileName=((fileName.indexOf("?")>=0)?fileName.substr(0,fileName.indexOf("?")):fileName)||"index.html";
}if(typeof $el=="undefined"){$el=$(".navigation-2-plugin");
}$el.find("li a").each(function(){var linkHref=$(this).attr("href").toLowerCase();
if(linkHref==fileName){$(this).parent().addClass("k-state-active").addClass("selected-page").addClass("k-state-highlight");
}else{$(this).parent().removeClass("k-state-active").removeClass("selected-page").removeClass("k-state-highlight");
}});
},ngPluginController:function($scope,$rootScope,$element){$scope.select=function(){if(typeof(neo.Navigation2Module)=="object"){neo.Navigation2Module.select($element);
}};
$scope.selectAndEdit=function(){var pmsId="#properties-module-shell";
var $ppScope=$(pmsId).scope();
if(!$(pmsId).hasClass("active")){neo.Navigation2Module.select($element);
}$ppScope.onSwapPropertyPanel();
};
$scope.onKendoMenuOpen=function(e){if(typeof neo.Navigation2Module!="undefined"){e.preventDefault();
}};
$scope.onKendoMenuSelect=function(e){if(typeof neo.Navigation2Module!="undefined"){e.preventDefault();
}};
}});
neo.CanvasPlugin={init:function(){this.autoAdjustMinHeight();
},autoAdjustMinHeight:function(){$("#canvas").css("min-height",0);
var canvasOuter=document.getElementById("canvas-outer");
var scrollHeight=webcom.util.getDocHeight();
if(canvasOuter){$("#canvas").css("min-height",canvasOuter.scrollHeight+"px");
}else{$("#canvas").css("min-height",scrollHeight+"px");
}if(webcom.util.isIE){$("#canvas").css("height","100px");
}}};
$(document).ready(function(){neo.CanvasPlugin.init();
$(window).resize(webcom.util.timerUtil.debounce(function(){neo.CanvasPlugin.autoAdjustMinHeight();
},500));
neo.CanvasPlugin.autoAdjustMinHeight();
});
neo.SnippetHtmlPlugin=neo.Plugin.extend({id:"SnippetHtml",});
neo.MediaPlugin=neo.Plugin.extend({id:"Media"});
neo.MapPlugin=neo.Plugin.extend({id:"Map",cssClass:"map-plugin",MAP_PROVIDER_URL:"http://www.mapquest.com/embed?icid=mqdist_webcom",MAP_DIRECTION_URL:"http://www.mapquest.com/?le=t",MAP_DEFAULT_ADDRESS:"601 Brasilia Ave, Kansas City, MO 64153",template:$(".map-plugin-inner").html(),renderMap:function(el,mapURL){$(el).find(".neo-asset-inner").html(mapURL);
},enableElement:function($el){var settings=$el.attr("data-settings");
if(typeof(settings)=="undefined"&&($(".neo-map").length>0)){var address=(webcom.common.UserService.getAddress()!=null)?webcom.common.UserService.getAddress():"";
var city=(webcom.common.UserService.getCity()!=null)?webcom.common.UserService.getCity():"";
var province=(webcom.common.UserService.getProvince()!=null)?webcom.common.UserService.getProvince():"";
var postalCode=(webcom.common.UserService.getPostalCode()!=null)?webcom.common.UserService.getPostalCode():"";
var country=(webcom.common.UserService.getCountry()!=null)?webcom.common.UserService.getCountry():"";
var addressToMap=address+" "+city+" "+province+" "+postalCode+" "+country;
var addressShow="";
if(addressToMap.trim().length>0){if(address.trim().length>0){addressShow='<div class="mapAddressShow"><span class="mapAddress">'+address+"<br/>"+city+", "+province+" "+postalCode+" "+country+"</span></div>";
}else{addressShow='<div class="mapAddressShow"><span class="mapAddress">'+city+", "+province+" "+postalCode+" "+country+"</span></div>";
}}else{addressShow='<div class="mapAddressShow"><span class="mapAddress">'+neo.MapPlugin.MAP_DEFAULT_ADDRESS+"</span></div>";
addressToMap=neo.MapPlugin.MAP_DEFAULT_ADDRESS;
}var mapURL='<div class="neo-mapquest"><iframe class="mapiframe" style="width:480px;height:245px;"  src="'+neo.MapPlugin.MAP_PROVIDER_URL+"&q="+encodeURIComponent(addressToMap)+'&zoom=13" ></iframe></div>';
neo.MapPlugin.renderMap($el,'<div class="neo-map-wrapper" style="width:480px;height:280px;">'+addressShow+mapURL+"</div>");
}$el.attr({"data-ng-controller":this.name+"Controller","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit()","data-module-class":this.moduleClass});
if(typeof(neo.MapModule)!="undefined"){neo.PropertiesNgModule.clickCloak.addClickCloak($el);
}neo.Plugin.bootstrap($el);
},});
neo.SocialPlugin=neo.Plugin.extend({id:"Social",ngPluginController:function($scope,$rootScope,$element){if(typeof(neo.SocialModule)=="object"){neo.PropertiesNgModule.clickCloak.addClickCloak($element);
}$scope.select=function(){if(typeof(neo.SocialModule)=="object"){neo.SocialModule.select($element);
}};
$scope.selectAndEdit=function(){if(typeof(neo.SocialModule)=="object"){var $ppScope=$("#properties-module-shell").scope();
$ppScope.onSwapPropertyPanel();
}};
}});
neo.LikePlugin=neo.Plugin.extend({id:"Like",name:"neo.LikePlugin",cssClass:"like-plugin",moduleClass:"neo.LikeModule",enableElement:function($el){$el.attr({"data-ng-controller":this.name+"Controller","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit()","data-module-class":this.moduleClass});
if(typeof(neo.LikeModule)=="object"){neo.PropertiesNgModule.clickCloak.addClickCloak($el);
}else{var iframe=$("iframe",$el);
var src=iframe.attr("src");
var newSrc=src.replace(/href=.*?&/,"href="+encodeURIComponent(document.location.href)+"&");
iframe.attr("src",newSrc);
}neo.Plugin.bootstrap($el);
}});
neo.SharePlugin=neo.Plugin.extend({id:"Share",name:"neo.SharePlugin",cssClass:"share-plugin",moduleClass:"neo.ShareModule",template:$(".share-plugin-inner").html(),reloadShareButtons:function(){var facebookShareButtons=$(".fb-share-button");
if(facebookShareButtons.length!=0){facebookShareButtons.each(function(i,facebookButton){var type=$(facebookButton).attr("data-type");
var assetInner=$(facebookButton).closest(".neo-asset-inner");
assetInner.html(neo.SharePlugin.template);
$(".fb-share-button-placeholder",assetInner).removeClass("fb-share-button-placeholder").addClass("fb-share-button");
$(".fb-share-button",assetInner).attr("data-type",type);
});
FacebookSdk.parse();
}},enableElement:function($el){$el.attr({"data-ng-controller":this.name+"Controller","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit()","data-module-class":this.moduleClass});
if(typeof(neo.ShareModule)=="object"){neo.PropertiesNgModule.clickCloak.addClickCloak($el);
}else{neo.SharePlugin.reloadShareButtons();
}FacebookSdk.initialize({windowOnLoad:true});
neo.Plugin.bootstrap($el);
}});
neo.GoogleSharePlugin=neo.Plugin.extend({id:"GoogleShare",name:"neo.GoogleSharePlugin",cssClass:"google-share-plugin",moduleClass:"neo.GoogleShareModule",template:$(".google-share-plugin-inner").html(),enableElement:function($el){$el.attr({"data-ng-controller":this.name+"Controller","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit()","data-module-class":this.moduleClass});
GooglePlus.initialize({windowOnLoad:true});
if(typeof neo.GoogleShareModule=="object"){neo.PropertiesNgModule.clickCloak.addClickCloak($el);
}else{var assetInner=$($el).find(".neo-asset-inner");
var options=$(".gplus-data",assetInner).data();
assetInner.html(neo.GoogleSharePlugin.template);
var button=$(".g-plus",assetInner);
var buttonData=$(".gplus-data",assetInner);
$.each(options,function(option,value){buttonData.attr("data-"+option,value);
button.attr("data-"+option,value);
});
GooglePlus.go("plus",buttonData.get(0));
}neo.Plugin.bootstrap($el);
}});
neo.GooglePlusOnePlugin=neo.Plugin.extend({id:"GooglePlusOne",name:"neo.GooglePlusOnePlugin",cssClass:"google-plusone-plugin",moduleClass:"neo.GooglePlusOneModule",template:$(".google-plusone-plugin-inner").html(),enableElement:function($el){$el.attr({"data-ng-controller":this.name+"Controller","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit()","data-module-class":this.moduleClass});
GooglePlus.initialize({windowOnLoad:true});
if(typeof neo.GooglePlusOneModule=="object"){neo.PropertiesNgModule.clickCloak.addClickCloak($el);
}else{var assetInner=$($el).find(".neo-asset-inner");
var options=$(".gplusone-data",assetInner).data();
options.href=document.location.url;
assetInner.html(neo.GooglePlusOnePlugin.template);
var button=$(".g-plusone",assetInner);
$.each(options,function(option,value){button.attr("data-"+option,value);
});
GooglePlus.go("plusone",$(".gplusone-data",assetInner).get(0));
}neo.Plugin.bootstrap($el);
}});
neo.TwitterPlugin=neo.Plugin.extend({id:"Twitter"});
neo.LinkedInSharePlugin=neo.Plugin.extend({id:"LinkedInShare",name:"neo.LinkedInSharePlugin",cssClass:"linkedin-share-plugin",moduleClass:"neo.LinkedInShareModule",enableElement:function($el){$el.attr({"data-ng-controller":this.name+"Controller","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit()","data-module-class":this.moduleClass});
if(typeof neo.LinkedInShareModule=="object"){neo.PropertiesNgModule.clickCloak.addClickCloak($el);
}else{$(".neo-asset."+neo.LinkedInSharePlugin.cssClass).each(function(i,plugin){var counter=$(plugin).find("script").attr("data-counter");
$(plugin).find(".neo-asset-inner").html(neo.LinkedInSharePlugin.getTemplate(counter));
});
neo.LinkedInSharePlugin.loadApi();
}neo.Plugin.bootstrap($el);
},getTemplate:function(counter){var dataShowZero=(counter=="right"?'data-showzero="true"':"");
return'<script type="IN/Share" '+dataShowZero+' data-counter="'+counter+'"><\/script>';
},loadApi:function(callback){if(document.getElementById("linkedin-api-loaded")){typeof callback!="undefined"?callback():1;
}else{var script=document.createElement("script");
script.id="linkedin-api-loaded";
script.async=true;
script.src="//platform.linkedin.com/in.js";
script.onload=function(){typeof callback!="undefined"?callback():1;
};
document.getElementsByTagName("body")[0].appendChild(script);
}}});
neo.FileDownloadLinkPlugin=neo.Plugin.extend({id:"FileDownloadLink",});
neo.TapPlugin=neo.Plugin.extend({id:"Tap",template:$(".tap-plugin-inner").html(),productTemplate:'<product data-pid="" data-tid="" data-lid=""></product>',accountDomain:"",init:function(){var t=this;
if(builderSettings.isBuilder){webcom.util.Events.register(neo.smc.events.tapAccountDomainUpdated,"TapPluginHandler",function(data){t.accountDomain=data.accountDomain;
});
}},enableElement:function($el){var t=neo.TapPlugin;
$el.attr({"data-ng-controller":t.name+"Controller","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit();","data-module-class":t.moduleClass});
if(builderSettings.isBuilder){if($el.find(".product-data").size()==1){t.prepareToRender($el);
}}else{if($el.find(".product-data").size()==0){var assetImageEl=$("img",$el);
var newImageEl=assetImageEl.clone();
var parsedUri=neo.URI(assetImageEl.attr("src"));
var imageFilename=parsedUri.filename();
newImageEl.attr("src",builderSettings.assetsRoot+"/plugins/revenue/tap/view/images/"+imageFilename);
assetImageEl.remove();
$(".neo-asset-inner",$el).append(newImageEl);
$el.width(newImageEl.width());
$el.height(newImageEl.height());
}else{t.prepareToRender($el);
}}neo.Plugin.bootstrap($el);
},windowLoaded:function(){var t=neo.TapPlugin;
if(builderSettings.isBuilder){var accountSrv=webcom.common.AccountService;
var ecommSrv=webcom.common.EcommService;
if(accountSrv.hasService("ecomm")&&ecommSrv.hasType("TakeAPayment")&&ecommSrv.getVersion()=="1.0"){t.reloadTapButtons();
webcom.util.Events.register(neo.smc.events.canvasSwitchPage,"TapPluginOnSwitchPage",t.onCanvasSwitchPage);
}}else{var firstTapElement=$("."+t.cssClass+" .product-data:first");
if(firstTapElement.size()==1){var tapJavascriptUrl=firstTapElement.attr("data-url");
if(tapJavascriptUrl.length!=0){var url=neo.URI(tapJavascriptUrl);
var hostname=url.hostname();
neo.TapLib.setAccountDomain(hostname);
neo.TapLib.render();
}}}},onCanvasSwitchPage:function(){var t=neo.TapPlugin;
t.reloadTapButtons();
},reloadTapButtons:function(){var t=neo.TapPlugin;
if(builderSettings.isBuilder){var hasTapDomain=(t.accountDomain.length>0);
if(hasTapDomain){neo.TapLib.render();
}else{t.resetTapAssets();
}}},resetTapAssets:function(){var t=neo.TapPlugin;
var assetConfig=neo.AssetConfig;
var pluginName="neo."+t.name;
for(var i=0;
i<assetConfig.revenue.length;
i++){if(assetConfig.revenue[i].pluginClass==pluginName){var tempElFromDropHtml=$(assetConfig.revenue[i].dropHtml);
var imageElInDropHtml=$("img",tempElFromDropHtml);
$("."+t.cssClass+" .neo-asset-inner").html(imageElInDropHtml);
$("."+t.cssClass).width(imageElInDropHtml.width());
$("."+t.cssClass).height(imageElInDropHtml.height());
neo.savePage();
break;
}}},prepareToRender:function(assetElement){var containerElWithData=$(".product-data",assetElement);
if(containerElWithData.size()==1){var productElement=$(neo.TapPlugin.productTemplate);
$(containerElWithData).html(productElement);
var productId=$(containerElWithData).attr("data-pid");
var layoutId=$(containerElWithData).attr("data-lid");
$(productElement).attr("data-pid",productId);
$(productElement).attr("data-lid",layoutId);
}}});
neo.TapLib={accountDomain:"",init:function(){var t=this;
if(builderSettings.isBuilder){webcom.util.Events.register(neo.smc.events.tapAccountDomainUpdated,"TapLibHandler",function(data){t.accountDomain=data.accountDomain;
});
}},load:function(){var t=neo.TapLib;
(function(d,id){window.IsMobile=false;
if(!d.getElementById(id)&&!window.aasLoaded){var js=d.createElement("script");
js.id=id;
js.type="text/javascript";
js.src=location.protocol+"//"+t.accountDomain+"/scripts/tap.min.js";
d.getElementsByTagName("head")[0].appendChild(js);
window.aasTag=document.createElement("product");
}}(document,"aas-js"));
},setAccountDomain:function(accountDomain){neo.TapLib.accountDomain=accountDomain;
},getAccountDomain:function(){return neo.TapLib.accountDomain;
},render:function(buttonElement){var t=neo.TapLib;
if($("#aas-js").size()==0){t.load();
}else{window.aasLoaded=false;
delete window.aasjQuery;
var randomInt=Math.round(Math.random()*100000);
(function(d,id){window.IsMobile=false;
if(!d.getElementById(id)&&!window.aasLoaded){var js=d.createElement("script");
js.id=id;
js.type="text/javascript";
js.src=location.protocol+"//"+t.accountDomain+"/scripts/tap.min.js?x="+randomInt;
d.getElementsByTagName("head")[0].appendChild(js);
window.aasTag=document.createElement("product");
}}(document,"aas-js-"+randomInt));
}}};
$(document).ready(function(){neo.TapLib.init();
});
$(window).load(function(){neo.TapPlugin.windowLoaded();
});
neo.GalleryPlugin=neo.Plugin.extend({id:"Gallery",enableElement:function($el){$el.attr({"data-ng-controller":this.name+"Controller","data-ng-click":"select();","data-ng-dblclick":"selectAndEdit()","data-module-class":this.moduleClass});
var data=$el.data("plugin-info");
$el.find(".neo-asset-inner").html('<div class="galleria" style="width: '+$el.width()+"px;height:"+$el.height()+'px;"></div>');
neo.Plugin.bootstrap($el);
var theme="classic";
try{var style=$el.data("style-info");
theme=style.theme;
}catch(exception){}neo.GalleryPlugin.loadThemeAndRun(theme,$el,data);
},loadThemeAndRun:function(themeName,$el,data){var theme=builderSettings.assetsRoot+"/libs/galleria/1.2.9/themes/classic/galleria.classic.min.js";
if(themeName=="slides"){theme=builderSettings.assetsRoot+"/libs/galleria/1.2.9/themes/web.slides/galleria.web.slides.js";
}else{if(themeName=="tiles"){theme=builderSettings.assetsRoot+"/libs/galleria/1.2.9/themes/web.tiles/galleria.web.tiles.js";
}}Galleria.unloadTheme();
Galleria.loadTheme(theme);
$el.find(".galleria").attr("style","width: "+$el.width()+"px;height:"+$el.height()+"px;");
Galleria.run($el.find(".galleria"),data);
Galleria.ready(function(options){var totalImages=parseInt(this.$("total").html());
if(this.getOptions("loopPlayBack")==false){this.bind("loadfinish",function(e){if(e.index==totalImages-1){this.pause();
}});
}this.bind("image",function(e){e.imageTarget.alt=e.galleriaData.title;
});
this.bind("thumbnail",function(e){e.thumbTarget.alt=e.galleriaData.title;
});
});
}});
neo.CheckoutPlugin=neo.Plugin.extend({id:"Checkout",template:'<span id="ecomm-items">0</span> items ($<span id="ecomm-price">0.00</span>) | <a href="checkout.html">Checkout</a>',construct:function($el){$el.find(".neo-asset-inner").html(neo.CheckoutPlugin.template);
}});
neo.ProductPlugin=neo.Plugin.extend({id:"Product",name:"ProductPlugin",init:function(){if(builderSettings.isBuilder){webcom.util.Events.register(neo.smc.events.ecommAddCheckoutWidget,"EcommAddCheckoutWidget",function(obj){neo.ProductPlugin.addCheckout();
});
}},autoAdjustMinHeight:function(){if(!builderSettings.isBuilder){if($("#product-detail").size()==1){var prodDetailHeight=$("#product-detail").height()+50;
$("#content .global-region-inner").height(prodDetailHeight);
}}},addEllipsisFunctionalityToProducts:function(){$(".product-title").dotdotdot({});
$(".product-description").dotdotdot({});
if(!builderSettings.isBuilder){$(".product-plugin").each(function(key,element){var $element=$(element);
$element.mouseenter(function(){$(".product-title",$element).trigger("destroy");
$(".product-description",$element).trigger("destroy");
}).mouseleave(function(){setTimeout(function(){$(".product-title",$element).dotdotdot({});
$(".product-description",$element).dotdotdot({});
},0);
});
});
}},construct:function($el){var isNew=this.checkIfNewProduct($el);
if(!isNew){this.addCheckout();
}},checkIfNewProduct:function($el){var isNew=false;
if($el.hasClass("new-product")&&builderSettings.isBuilder){isNew=true;
}else{}return isNew;
},addCheckout:function(){var $checkout=$(".checkout-plugin");
if($checkout.length==0){console.log("Add to cart button detected without checkout cart, adding checkout cart");
var $checkout=$('<div class="checkout-plugin neo-asset neo-jailed neo-disabled-actions neo-not-resizable" style="width:170px;height:20px;position:absolute;right:0;top: 0;"><div class="neo-asset-inner">This is a checkout box</div></div>');
$(".global-region.top .global-region-inner").append($checkout);
if(builderSettings.isBuilder){CanvasModule.setupAssetEvents($checkout);
var distance=$checkout.height();
CanvasModule.toggleHeaderAssetsPosition(distance,"PUSH",$checkout);
}webcomApp.enableByElement($checkout);
}}});
$(document).ready(function(){neo.ProductPlugin.init();
neo.ProductPlugin.autoAdjustMinHeight();
neo.ProductPlugin.addEllipsisFunctionalityToProducts();
});
neo.PaymentPlugin=neo.Plugin.extend({id:"Payment",name:"PaymentPlugin",construct:function($el){if(!builderSettings.isBuilder){if($el.css("cursor")=="auto"){$el.css("cursor","pointer");
}$el.bind("click",function(){neo.PaymentPlugin.addToCartAndRedirectToCheckout($el);
});
}},addToCartAndRedirectToCheckout:function($el){if($el.hasClass("payment-plugin")){alert("Payment was clicked! ");
}}});
neo.DonationPlugin=neo.Plugin.extend({id:"Donation",name:"DonationPlugin",construct:function($el){if(!builderSettings.isBuilder){if($el.css("cursor")=="auto"){$el.css("cursor","pointer");
}$el.bind("click",function(){neo.DonationPlugin.addToCartAndRedirectToCheckout($el);
});
}},addToCartAndRedirectToCheckout:function($el){if($el.hasClass("donation-plugin")){alert("Donation was clicked! ");
}}});
